# Generated by Django 4.1.7 on 2023-02-19 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=300)),
                ('appartment_square', models.IntegerField()),
                ('appartment_floor', models.IntegerField()),
                ('floors_count', models.IntegerField()),
                ('marketing_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parserAvitoCian.source')),
            ],
        ),
    ]
